improve performance when grabbing module posts.
helsingborg-stad/Modularity pull request #310
Opened 2022-10-18 03:49 UTC by Zerowalker

using `$wpdb` and only getting the ID has quite a bit less overhead compared to `get_posts`.

As the results are cached this only affects the first run each instance.

I'm unsure what the preferred formatting is for the project,
and i probably broken some here (at least on the `$format_statement`):p

2022-10-18 03:51 UTC, Zerowalker commented
hmm not sure i did this right, i just wanted to pull request on the last commit.
not that familiar with pull requests and merging etc so i might have messed up, just shout out if that's the case:)

2022-10-19 11:56 UTC, sebastianthulin commented
A core principle in the Muncipio productis is readability before performance. I can't see that this change comply with this principle. Also: WordPress introduced caching on multiple levels regarding wpquery. This may interfere with these changes theoretically. Needs through testing.

2022-10-20 04:13 UTC, Zerowalker commented
Understandable, I would love feedback on how to make it more readable in case tests show it's improvements,
as sadly I am a bit blind wen it comes to readability at times, but here I at least see that the parts I mentioned are convoluted.
Though not sure how to improve it without making a separate `function` which perhaps it's preferred either?

When did WordPress introduce these caching?
I have tested this change on `6.0.3`.

Here's results from a test server using: `ab -n 100 -c 1`

Empty page (no modules, `get_posts`)
```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        1    1   0.0      1       1
Processing:   150  153   2.8    152     164
Waiting:      149  153   2.8    152     164
Total:        151  154   2.9    153     165
```
Empty page (no modules, `wpdb`)
```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        1    1   0.1      1       1
Processing:    85   91   5.6     90     115
Waiting:       85   91   5.5     89     115
Total:         86   92   5.6     90     116
```

page with some modules (`get_posts`)
```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        1    1   0.0      1       1
Processing:   116  121   5.7    121     169
Waiting:      115  121   5.7    120     169
Total:        116  122   5.7    122     170
```
page with some modules (`wpdb`)
```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        1    1   0.1      1       1
Processing:   117  119   2.6    118     134
Waiting:      117  119   2.6    118     134
Total:        118  120   2.6    119     135
```


For some reason the performance boost occurs there's no modules which i find odd.
Now if it's seen as too small I'm not going to show it down your throat of course, it's just a suggestion based on the what I concluded was an improvement based on my test results, I will gladly take critique if it's wrong in any way:)

2022-11-24 10:24 UTC, sebastianthulin commented
I have read some documentation on the 6.0.3 release of WordPress. It seems that this change will work, ie. cache will be banned for posts whenever they are updated. Some issues may appear on JOIN querys, but that is not relevant here.

2022-11-24 10:29 UTC, sebastianthulin requested changes

2022-11-24 10:29 UTC, sebastianthulin commented on source/php/Editor.php
> +            $format_statement = fn ($a, $raw = false) => implode(',', $raw ? $a : array_map(fn ($v) => "'" . esc_sql($v) . "'", $a));
This may be clarified, might work better as a multiline function or split to a new function.

2022-11-24 10:29 UTC, sebastianthulin commented on source/php/Editor.php
> +            if (!empty($modulesPosts)) {
A check if this is an array ight be suitable. I understand that this might be out of scope.

2022-11-24 10:29 UTC, sebastianthulin commented on source/php/Editor.php
> +                    $modules[$module->ID] = $module;
A check if this is an valid object might be suitable. I understand that this might be out of scope.

2022-11-24 10:32 UTC, sebastianthulin commented
> Understandable, I would love feedback on how to make it more readable in case tests show it's improvements, as sadly I am a bit blind wen it comes to readability at times, but here I at least see that the parts I mentioned are convoluted. Though not sure how to improve it without making a separate `function` which perhaps it's preferred either?
> 
> When did WordPress introduce these caching? I have tested this change on `6.0.3`.
> 
> Here's results from a test server using: `ab -n 100 -c 1`
> 
> Empty page (no modules, `get_posts`)
> 
> ```
> Connection Times (ms)
>               min  mean[+/-sd] median   max
> Connect:        1    1   0.0      1       1
> Processing:   150  153   2.8    152     164
> Waiting:      149  153   2.8    152     164
> Total:        151  154   2.9    153     165
> ```
> 
> Empty page (no modules, `wpdb`)
> 
> ```
> Connection Times (ms)
>               min  mean[+/-sd] median   max
> Connect:        1    1   0.1      1       1
> Processing:    85   91   5.6     90     115
> Waiting:       85   91   5.5     89     115
> Total:         86   92   5.6     90     116
> ```
> 
> page with some modules (`get_posts`)
> 
> ```
> Connection Times (ms)
>               min  mean[+/-sd] median   max
> Connect:        1    1   0.0      1       1
> Processing:   116  121   5.7    121     169
> Waiting:      115  121   5.7    120     169
> Total:        116  122   5.7    122     170
> ```
> 
> page with some modules (`wpdb`)
> 
> ```
> Connection Times (ms)
>               min  mean[+/-sd] median   max
> Connect:        1    1   0.1      1       1
> Processing:   117  119   2.6    118     134
> Waiting:      117  119   2.6    118     134
> Total:        118  120   2.6    119     135
> ```
> 
> For some reason the performance boost occurs there's no modules which i find odd. Now if it's seen as too small I'm not going to show it down your throat of course, it's just a suggestion based on the what I concluded was an improvement based on my test results, I will gladly take critique if it's wrong in any way:)

I would think that get_posts with an empty result isen't a valid cachable result. Therefore, an empty reposne (no modules) is slower than a page with modules. This is however nothing i have verified.

2022-12-08 05:19 UTC, Zerowalker commented on source/php/Editor.php
> +                    $modules[$module->ID] = $module;
From my understanding you either get an object, array or null.
empty will check if it's an empty array or null, but not sure of the object part,
will it return an object if it's 1 result, or is it dependent on the query?

2022-12-08 05:33 UTC, Zerowalker commented on source/php/Editor.php
> +            if (!empty($modulesPosts)) {
added checks

2022-12-08 05:33 UTC, Zerowalker commented on source/php/Editor.php
> +            $format_statement = fn ($a, $raw = false) => implode(',', $raw ? $a : array_map(fn ($v) => "'" . esc_sql($v) . "'", $a));
tried clarifying it

2023-01-04 13:26 UTC, closed without merging