Use correct post dates
helsingborg-stad/Modularity pull request #324
Opened 2022-11-07 10:07 UTC by annalinneajohansson

2022-11-07 10:07 UTC, helsingborgsstad commented
Task linked: [CU-3qnp7u7 fel publiceringsdatum posts-modul kulturkortet.se startsida](https://app.clickup.com/t/3qnp7u7)

2022-11-07 15:55 UTC, sebastianthulin commented on source/php/Module/Posts/views/features-grid.blade.php
> +                'date' => $post->showDate ? date("Y-m-d H:i", strtotime($post->post_date)) : false,
Use WordPress date format set in settings panel.

2022-11-07 15:55 UTC, sebastianthulin commented on source/php/Module/Posts/views/partials/date.blade.php
> +@if($post->postDate)z
z?

2022-11-08 10:58 UTC, sebastianthulin requested changes
Needs to use WordPress date format from settings.

2022-11-08 18:48 UTC, merged