truncate posts init
helsingborg-stad/Modularity pull request #388
Opened 2023-03-21 10:01 UTC by NiclasNorin

2023-03-22 07:45 UTC, annalinneajohansson reviewed
I would propose setting post_content in either AbstractController if the truncation is to be done in all views, or on each respective controller.

2023-03-22 19:31 UTC, NiclasNorin commented
> I would propose setting post_content in either AbstractController if the truncation is to be done in all views, or on each respective controller.

I will try this, I believe that expandable list is meant to show everything. But i will test to see if it works.

2023-03-23 11:02 UTC, sebastianthulin requested changes

2023-03-23 11:03 UTC, sebastianthulin commented on source/php/Module/Posts/Helper/Truncate.php
> +        return implode(' ', $truncate) . $readMore;
Also. What will happen if there are a "more" tag in content? I would assume as a user that my content't isen't truncated then. Or manual input is used.

2023-03-23 11:42 UTC, closed without merging