feature/Ny modul Modal CU 865cn09xb
helsingborg-stad/Modularity pull request #441
Opened 2023-07-03 13:57 UTC by annalinneajohansson

- (add) ACF fields for module Modal
- (add) New module "Modal"

2023-07-03 13:57 UTC, helsingborgsstad commented
Task linked: [CU-865cn09xb Ny modul: Modal](https://app.clickup.com/t/865cn09xb)

2023-07-07 11:42 UTC, sebastianthulin requested changes
Small changes, otherwise great!

2023-07-07 11:42 UTC, sebastianthulin commented on source/php/Module/Modal/Modal.php
> +    public function disallowBlockType($allowedBlockTypes, $editorContext)
Can be replaced with this option on module creation. 
https://github.com/helsingborg-stad/Modularity/blob/3.0/develop/source/php/Module.php#L105

2023-07-07 11:42 UTC, sebastianthulin commented on source/php/Module/Modal/Modal.php
> +        $fields = get_fields($this->ID);
Use https://github.com/helsingborg-stad/Modularity/blob/3.0/develop/source/php/Module.php#L284 instead.

2023-07-24 08:19 UTC, annalinneajohansson commented on source/php/Module/Modal/Modal.php
> +    public function disallowBlockType($allowedBlockTypes, $editorContext)
I'm not following your thought here; can you please explain?

2023-08-07 12:56 UTC, merged