Feature/trigga save post nr du klickar p spara p spara moduler cu 8693v3uxu
helsingborg-stad/Modularity pull request #613
Opened 2024-03-25 06:19 UTC by annalinneajohansson

2024-03-25 06:19 UTC, helsingborgsstad commented
Task linked: [CU-8693v3uxu Trigga save_post när du klickar på "Spara" på Spara moduler](https://app.clickup.com/t/8693v3uxu)

2024-03-25 14:33 UTC, NiclasNorin commented on phpunit.xml
> +      <directory suffix=".test.php">source/php</directory>
This should not be changed. Tests are currently placed outside of the source folder. Check here:
https://github.com/helsingborg-stad/Municipio/tree/main/tests/phpunit

2024-03-27 07:34 UTC, thorbrink requested changes

2024-03-27 07:34 UTC, thorbrink commented on source/php/BlockManager.php
> +                        error_log($error->get_error_message());
Remove WP_Error and pass error message to error_log directly.

2024-03-27 07:34 UTC, thorbrink commented on source/php/Editor.php
> +            update_post_meta($postId, 'modularity-sidebar-options', $_POST['modularity_sidebar_options']);
Sanitize POST data before use.

2024-03-31 18:28 UTC, sebastianthulin commented on source/php/Editor.php
> +            delete_post_meta($postId, 'modularity-sidebar-options');
Sanitize need

2024-04-02 08:28 UTC, sebastianthulin approved these changes

2024-04-02 08:28 UTC, merged