feat: cleaning of the contact module
helsingborg-stad/Modularity pull request #677
Opened 2024-10-09 14:20 UTC by sebastianthulin

This is not a refactor. It's simply a cleanup phase, in order to understand the module better in order to refine the modules functionality and purpose later on.

2024-10-09 14:24 UTC, NiclasNorin commented on source/php/Module/Contacts/Contacts.php
> +            $titlePropeties = ['administration_unit', 'work_title'];
Misspelled

2024-10-09 14:24 UTC, NiclasNorin commented on source/php/Module/Contacts/Contacts.php
> +            }, $titlePropeties), function($item) {return $item;});
Same as above

2024-10-09 14:28 UTC, NiclasNorin commented on source/php/Module/Contacts/views/cards.blade.php
> +<div class="o-grid o-grid--half-gutter" aria-labelledby={{'mod-text-' . $ID .'-label'}}>
Missing quotes around inside aria-labelledby

2024-10-09 14:30 UTC, NiclasNorin commented on source/php/Module/Contacts/views/cards.blade.php
> +                @if(array_filter([!empty($contact['email']), !empty($contact['phone'])]))
Isnt it better to use @if(!empty($contact['email']) || !empty($contact['phone']))?

2024-10-09 14:31 UTC, NiclasNorin commented on source/php/Module/Contacts/views/cards.blade.php
> +                        @includeWhen(!empty($contact['address']), 'components.adress')
Misspelled "address"

2024-10-09 14:32 UTC, NiclasNorin commented on source/php/Module/Contacts/views/cards.blade.php
> +                                @include('components.phone', ['icon' => 'phone'])
Should $phone not be passed to the component?

2024-10-09 14:35 UTC, NiclasNorin requested changes
Small changes

2024-10-11 12:02 UTC, sebastianthulin commented on source/php/Module/Contacts/Contacts.php
> +            }, $titlePropeties), function($item) {return $item;});
Fixed

2024-10-11 12:03 UTC, sebastianthulin commented on source/php/Module/Contacts/views/cards.blade.php
> +                        @includeWhen(!empty($contact['address']), 'components.adress')
Spelled this way in whole codebase. Wont fix. Will be resolved when converting to component.

2024-10-11 12:03 UTC, sebastianthulin commented on source/php/Module/Contacts/views/cards.blade.php
> +                                @include('components.phone', ['icon' => 'phone'])
Won't really matter, but fixed.

2024-10-11 12:03 UTC, merged